name: geosimpleclassify_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - geopandas
  - rasterio
  - scikit-learn
  - matplotlib-base

  # notebook
  - ipykernel
  - ipython
  - jupyterlab
